#Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "pierre"
  config.vm.network "public_network", type: "static", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |v|
    v.name = "pierre_name"
    v.memory = 4096
    v.cpus = 4
  end

  # check_guest_additions
  
  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  #config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
