#Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos7k8s"
  config.vm.network "private_network", ip:"192.168.56.10"
  config.vm.provider "virtualbox" do |v|
    v.name = "centos7_k8s"
    v.memory = 4096
    v.cpus = 4
  end
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
