- name: Install desktop environment
  block:
    - name: Install the Gnome desktop environment group
      yum:
        name: "@^gnome-desktop-environment"
        state: present

    - name: Create .xinitrc
      copy: 
        dest: "/home/vagrant/.xinitrc"
        content: "exec gnome-session" 

    - name: Set graphical session permanently
      file: 
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link


- name: Install docker
  block:
    - name: Install yum-utils
      package:
        name: yum-utils
        state: latest


    - name: Add docker-ce repo
      command: 
        cmd: yum-config-manager --add-repo "https://download.docker.com/linux/centos/docker-ce.repo"

    - name: Install docker packages
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - containerd.io
        state: latest

    - name: Add user to docker group
      user:
        name: vagrant
        group: docker
        append: yes

    - name: Start docker
      systemd:
        state: started
        name: docker
        enabled: yes

- name: Install minikube
  block:
    - name: Install packages required in k8s training environement
      package:
        name: "{{ packages }}"
        state: latest

    - name: Start libvirtd
      systemd:
        state: started
        name: libvirtd
        enabled: yes

    - name: Add user to the libvirt group
      user:
        name: vagrant
        groups: libvirt
        append: yes
      register: libvirt_flag

          # check that /etc/libvirt/libvirtd.conf contains : 
            # unix_sock_group = "libvirt" 
            # unix_sock_rw_perms = "0770"
    
    - name: restart libvirtd
      systemd:
        state: restarted
        name: libvirtd
      when: libvirt_flag.changed


    - name: Download minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /home/vagrant/
        owner: vagrant
        mode: '0750'
        force: no


    - name: Move minikube to /usr/local/bin
      file:
        src: /home/vagrant/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        state: hard

- name: Move kubernetes labs resources in VM
  block:
    - name: Move resources folder to VM
      copy:
        src: ./resources
        dest: /home/vagrant
        owner: vagrant
        group: vagrant
        mode: '0744'



