Vagrant.require_version ">= 2.0.0"

boxes = [
    {
        :name => "master",
        :eth1 => "192.168.205.100",
        :mem => "4096",
        :cpu => "2"
    },
    {
        :name => "worker1",
        :eth1 => "192.168.205.101",
        :mem => "2048",
        :cpu => "1"
    },
    {
        :name => "worker2",
        :eth1 => "192.168.205.102",
        :mem => "2048",
        :cpu => "1"
    }

]

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"

  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
          v.name = opts[:name]
        end
        config.vm.network :private_network, ip: opts[:eth1]
      end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.groups = {
      "masters" => ["master"],
      "workers" => ["worker1", "worker2"]
    }
  end

end
