- name: Install desktop environment
  block:
    - name: Install the Gnome desktop environment group
      yum:
        name: "@^gnome-desktop-environment"
        state: present

    - name: Create .xinitrc
      copy: 
        dest: "/home/vagrant/.xinitrc"
        content: "exec gnome-session" 

    - name: Set graphical session permanently
      file: 
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link


          #- name: Install docker


- name: Install minikube
  block:
    - name: Install packages required in k8s training environement
      package:
        name: "{{ packages }}"
        state: latest

    - name: Start libvirtd
      systemd:
        state: started
        name: libvirtd
        enabled: yes

    - name: Add user to the libvirt group
      user:
        name: vagrant
        groups: libvirt
        append: yes
      register: libvirt_flag

          # check that /etc/libvirt/libvirtd.conf contains : 
            # unix_sock_group = "libvirt" 
            # unix_sock_rw_perms = "0770"
    
    - name: restart libvirtd
      systemd:
        state: restarted
        name: libvirtd
      when: libvirt_flag.changed


    - name: Download minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /home/vagrant/
        owner: vagrant
        mode: '0750'


    - name: Move minikube to /usr/local/bin
      file:
        src: /home/vagrant/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        state: hard

          #curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          #chmod +x kubectl
          #sudo mv kubectl  /usr/local/bin/
